Repository Himedia-bootcamp/MarketNawa.Crawling, pull requests merged in 2024-07, with the labels that each got.

#2 Init: elasticsearch save 보일러코드 추가
  src/main/kotlin/marketnawa/controller/TestController.kt
  src/main/kotlin/marketnawa/domain/Category.kt
  src/main/kotlin/marketnawa/elasitcsearch/ElasticsearchConfig.kt
Labels: ✨ Feature

#5 [Feat] 검색엔진 보완 및 검색,인덱싱가능하도록 보완
  src/main/kotlin/marketnawa/Application.kt
  src/main/kotlin/marketnawa/crawling/product/coupang/coupangCrawling.kt
  src/main/kotlin/marketnawa/crawling/product/gmarket/gmarketCrawling.kt
  src/main/kotlin/marketnawa/crawling/product/ssg/ssgCrawling.kt
  src/main/kotlin/marketnawa/elasitcsearch/ElasticsearchProperties.kt
  src/main/kotlin/marketnawa/elasitcsearch/EsSearchService.kt
  src/main/kotlin/marketnawa/healthcheck/controller/HealthCheckController.kt
  src/main/kotlin/marketnawa/util/ElasticsearchUtil.kt
  src/main/kotlin/marketnawa/util/ElasticsearchUtil2.kt
  src/main/kotlin/marketnawa/util/IndexingUtil.kt
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#7 [Feat] : 인덱스 필드 수정
  src/main/kotlin/marketnawa/crawling/product/coupang/coupangCrawling.kt
  src/main/kotlin/marketnawa/crawling/product/gmarket/gmarketCrawling.kt
  src/main/kotlin/marketnawa/crawling/product/ssg/ssgCrawling.kt
Labels: ✨ Feature, 🔨 Refactor
